### ISSUE TITLE
Option to select file types to match in

### ISSUE THREAD

**Issue by emoon** [ariaci/VSRipGrep#1]
Hi, First of all thanks for this project.

Something that would be nice would be ability to select which file types to search in (such as `*.cpp;*.h`) that you can set for the regular find in files.

**Comment by ariaci** [comment]
Hi, such option is already implemented but I've not released new version of my plugin. Please wait some days - I'll try to publish an updated version giving the ability to select file types search in.

**Comment by emoon** [comment]
Ah great! Thanks :)

**Comment by ariaci** [comment]
New version 1.0.1-preview published at marketplace supporting file types selection
